# Generated by Django 3.2.12 on 2022-03-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctor_name_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_details',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
