# Generated by Django 3.2.12 on 2022-03-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_doctor_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_details',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
